[tool.poetry]
name = "people"
version = "0.1.0"
description = "People service"
authors = ["Collin Mutembei <collin@solublecode.dev>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
fastapi = "^0.109.1"
beanie = "^1.25.0"
fastapi-users = {version = "^12.1.2", extras = ["redis", "beanie", "oauth"]}
loguru = "^0.7.2"
python-decouple = "^3.8"
phonenumbers = "^8.13.23"
uvicorn = {version = "^0.23.2", extras = ["standard"]}
python-magic = "^0.4.27"
pandas = ">=2.0.0"
minio = "^7.2.3"
fastapi-mail = "^1.4.1"
pydantic-settings = "^2.1.0"
numpy = "^1.26.1"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
ipython = "^8.18.1"
jsf = "^0.8.0"
pytest-asyncio = "^0.21.1"
setuptools = "^68.2.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
