"""init

Revision ID: f6a5a68127f8
Revises: 
Create Date: 2021-09-21 19:01:00.105148

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f6a5a68127f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('bio', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_profiles_active'), 'profiles', ['active'], unique=False)
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.create_table('socials',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('network', sa.Enum('FACEBOOK', 'TWITTER', 'INSTAGRAM', 'TIKTOK', name='socialaccountproviders'), nullable=True),
    sa.Column('account_url', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('profile_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_url')
    )
    op.create_index(op.f('ix_socials_id'), 'socials', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_socials_id'), table_name='socials')
    op.drop_table('socials')
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_active'), table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
